/** Skills the matcher can recognize. Longer aliases are counted before shorter ones. */
const SKILL_CATALOG = [
  { name: 'Python', aliases: ['python', 'python3'] },
  { name: 'SQL', aliases: ['postgresql', 'postgres', 'mysql', 't-sql', 'tsql', 'sql'] },
  { name: 'Spark', aliases: ['apache spark', 'pyspark', 'spark'] },
  { name: 'PySpark', aliases: ['pyspark'] },
  { name: 'Kafka', aliases: ['apache kafka', 'kafka'] },
  { name: 'Airflow', aliases: ['apache airflow', 'airflow'] },
  { name: 'dbt', aliases: ['dbt core', 'dbt'] },
  { name: 'Snowflake', aliases: ['snowflake'] },
  { name: 'BigQuery', aliases: ['bigquery', 'big query'] },
  { name: 'Redshift', aliases: ['redshift'] },
  { name: 'Databricks', aliases: ['databricks'] },
  { name: 'Pandas', aliases: ['pandas'] },
  { name: 'NumPy', aliases: ['numpy'] },
  { name: 'Hadoop', aliases: ['hadoop'] },
  { name: 'Hive', aliases: ['apache hive', 'hive'] },
  { name: 'Flink', aliases: ['apache flink', 'flink'] },
  { name: 'Java', aliases: ['java'] },
  { name: 'Scala', aliases: ['scala'] },
  { name: 'JavaScript', aliases: ['javascript', 'node.js', 'nodejs'] },
  { name: 'TypeScript', aliases: ['typescript'] },
  { name: 'Go', aliases: ['golang'] },
  { name: 'Bash', aliases: ['bash', 'shell scripting'] },
  { name: 'R', aliases: ['r programming', 'rstudio', 'tidyverse'] },
  { name: 'AWS', aliases: ['amazon web services', 'aws'] },
  { name: 'S3', aliases: ['amazon s3', 's3'] },
  { name: 'EMR', aliases: ['amazon emr', 'emr'] },
  { name: 'Glue', aliases: ['aws glue', 'glue'] },
  { name: 'Athena', aliases: ['amazon athena', 'athena'] },
  { name: 'Lambda', aliases: ['aws lambda'] },
  { name: 'GCP', aliases: ['google cloud', 'gcp'] },
  { name: 'Dataflow', aliases: ['cloud dataflow', 'dataflow'] },
  { name: 'Azure', aliases: ['microsoft azure', 'azure'] },
  { name: 'Azure Data Factory', aliases: ['azure data factory', 'adf'] },
  { name: 'Azure Databricks', aliases: ['azure databricks'] },
  { name: 'Azure Synapse', aliases: ['azure synapse', 'synapse analytics'] },
  { name: 'ADLS', aliases: ['adls gen2', 'azure data lake storage', 'azure data lake', 'adls'] },
  { name: 'Azure SQL', aliases: ['azure sql'] },
  { name: 'Azure DevOps', aliases: ['azure devops'] },
  { name: 'Microsoft Fabric', aliases: ['microsoft fabric'] },
  { name: 'Docker', aliases: ['docker'] },
  { name: 'Kubernetes', aliases: ['kubernetes', 'k8s'] },
  { name: 'Terraform', aliases: ['terraform'] },
  { name: 'Git', aliases: ['github', 'gitlab', 'git'] },
  { name: 'CI/CD', aliases: ['ci/cd', 'continuous integration', 'continuous delivery', 'github actions'] },
  { name: 'Linux', aliases: ['linux'] },
  { name: 'ETL', aliases: ['elt pipelines', 'etl pipelines', 'etl', 'elt'] },
  { name: 'Data Modeling', aliases: ['dimensional modeling', 'star schema', 'data modeling', 'data modelling'] },
  { name: 'Data Pipelines', aliases: ['data pipelines', 'data pipeline'] },
  { name: 'Data Warehousing', aliases: ['data warehousing', 'data warehouse'] },
  { name: 'Data Quality', aliases: ['data quality', 'data validation'] },
  { name: 'Streaming', aliases: ['stream processing', 'streaming data', 'real-time streaming'] },
  { name: 'Tableau', aliases: ['tableau'] },
  { name: 'Power BI', aliases: ['power bi', 'powerbi'] },
  { name: 'Looker', aliases: ['looker'] },
  { name: 'Excel', aliases: ['microsoft excel', 'excel'] },
  { name: 'Machine Learning', aliases: ['machine learning', 'ml models'] },
  { name: 'scikit-learn', aliases: ['scikit-learn', 'scikit learn', 'sklearn'] },
  { name: 'TensorFlow', aliases: ['tensorflow'] },
  { name: 'PyTorch', aliases: ['pytorch', 'py torch'] },
  { name: 'Keras', aliases: ['keras'] },
  { name: 'XGBoost', aliases: ['xgboost'] },
  { name: 'MLflow', aliases: ['mlflow'] },
  { name: 'NLP', aliases: ['natural language processing', 'nlp'] },
  { name: 'Computer Vision', aliases: ['computer vision'] },
  { name: 'Feature Engineering', aliases: ['feature engineering'] },
  { name: 'Feature Store', aliases: ['feature store', 'feature stores'] },
  { name: 'Model Deployment', aliases: ['model deployment', 'model serving', 'deploying models'] },
  { name: 'Model Monitoring', aliases: ['model monitoring'] },
  { name: 'Statistics', aliases: ['statistical analysis', 'hypothesis testing', 'statistics'] },
  { name: 'A/B Testing', aliases: ['a/b testing', 'ab testing', 'a/b tests'] },
  { name: 'Experimentation', aliases: ['online experiments', 'experimentation'] },
  { name: 'REST APIs', aliases: ['rest api', 'rest apis', 'restful'] },
  { name: 'PostgreSQL', aliases: ['postgresql', 'postgres'] },
];

const KEYWORD_PHRASES = [
  'medallion architecture',
  'slowly changing dimensions',
  'change data capture',
  'data contracts',
  'data governance',
  'data observability',
  'business intelligence',
  'stakeholder communication',
  'cross-functional',
  'infrastructure as code',
  'production support',
  'code review',
  'unit testing',
  'cost optimization',
  'real-time analytics',
  'batch processing',
  'version control',
  'predictive modeling',
  'experiment tracking',
  'causal inference',
  'technical leadership',
  'root cause analysis',
  'incremental models',
  'mlops',
  'on-call',
  'mentoring',
  'orchestration',
  'data lake',
  'kpi dashboards',
  'clickstream',
  'feature pipelines',
];

module.exports = { SKILL_CATALOG, KEYWORD_PHRASES };
